//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.02 at 02:53:04 PM IST 
//


package com.shopdirect.ws.xsd.accountstatus;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for custStatusDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="custStatusDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="com.lsdg.ws.AccountStatus.AccountStatusObjects.CustStatusDetails" type="{http://ws.shopdirect.com/xsd/AccountStatus}com.lsdg.ws.AccountStatus.AccountStatusObjects.CustStatusDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "custStatusDetails", propOrder = {
    "comLsdgWsAccountStatusAccountStatusObjectsCustStatusDetails"
})
public class CustStatusDetails {

    @XmlElement(name = "com.lsdg.ws.AccountStatus.AccountStatusObjects.CustStatusDetails")
    protected ComLsdgWsAccountStatusAccountStatusObjectsCustStatusDetails comLsdgWsAccountStatusAccountStatusObjectsCustStatusDetails;

    /**
     * Gets the value of the comLsdgWsAccountStatusAccountStatusObjectsCustStatusDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ComLsdgWsAccountStatusAccountStatusObjectsCustStatusDetails }
     *     
     */
    public ComLsdgWsAccountStatusAccountStatusObjectsCustStatusDetails getComLsdgWsAccountStatusAccountStatusObjectsCustStatusDetails() {
        return comLsdgWsAccountStatusAccountStatusObjectsCustStatusDetails;
    }

    /**
     * Sets the value of the comLsdgWsAccountStatusAccountStatusObjectsCustStatusDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComLsdgWsAccountStatusAccountStatusObjectsCustStatusDetails }
     *     
     */
    public void setComLsdgWsAccountStatusAccountStatusObjectsCustStatusDetails(ComLsdgWsAccountStatusAccountStatusObjectsCustStatusDetails value) {
        this.comLsdgWsAccountStatusAccountStatusObjectsCustStatusDetails = value;
    }

}
