//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.02 at 01:26:37 PM IST 
//


package com.shopdirect.ws.xsd.accountstatus;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for custStatusDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="custStatusDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="custStatusDetailsList" type="{http://ws.shopdirect.com/xsd/AccountStatus}custStatusDetailsList" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "custStatusDetails", propOrder = {
    "custStatusDetailsList"
})
public class CustStatusDetails {

    @XmlElement(required = true)
    protected List<CustStatusDetailsList> custStatusDetailsList;

    /**
     * Gets the value of the custStatusDetailsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the custStatusDetailsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustStatusDetailsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustStatusDetailsList }
     * 
     * 
     */
    public List<CustStatusDetailsList> getCustStatusDetailsList() {
        if (custStatusDetailsList == null) {
            custStatusDetailsList = new ArrayList<CustStatusDetailsList>();
        }
        return this.custStatusDetailsList;
    }

	public void setCustStatusDetailsList(List<CustStatusDetailsList> custStatusDetailsList) {
		this.custStatusDetailsList = custStatusDetailsList;
	}

}
